default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'bhcards' %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bhcards_development
  password: bhcards

test:
  <<: *default
  database: bhcards_test
  password: bhcards

production:
  <<: *default
  database: bhcards_production
